apiVersion: batch/v1
kind: Job
metadata:
  name: emxq-set-admin-password
  annotations:
    "helm.sh/hook": post-install, post-upgrade  # Always make sure the admin password is as expected
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: emxq-set-admin-password
    spec:
      restartPolicy: Never
      serviceAccountName: emxq-generate-admin-password
      volumes:
        - name: &kube kube
          emptyDir: {}
      containers:
      - name: set-password
        image: {{ template "kubectl" .Capabilities.KubeVersion }}
        volumeMounts:
          - name: *kube
            mountPath: /.kube
        command:
          - bash
          - '-c'
          - |
            set -exo pipefail

            sleep 5 # Wait for networking
            EMQX_ADMIN_PASS=$(kubectl get secret emx-admin-credentials -ojson | jq -r '.data.password | @base64d')
            kubectl wait pods --selector apps.emqx.io/instance=emqx --for condition=Ready --timeout=90s
            kubectl exec svc/emqx-headless -- emqx ctl admins passwd admin $EMQX_ADMIN_PASS
