apiVersion: batch/v1
kind: Job
metadata:
  name: "crypto-ingress-setup"
  labels:
    app: crypto-ingress-setup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      name: "crypto-ingress-setup"
      labels:
        app: crypto-ingress-setup
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      containers:
      - name: pre-upgrade-job
        image: "{{ .Values.image.repositoryBase }}/crypto-ingress:{{ .Values.image.tag }}"
        command: ["python3", "-m", "crypto_ingress.scripts.configure_buckets"]
        env:
          {{- include "crypto-ingress.env" . | nindent 12 }}
