apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telesys-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt-prod"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: telesys.k3s.mmaton.com
    http:
      paths:
      - backend:
          service:
            name: telesys-api
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - telesys.k3s.mmaton.com
    secretName: tls-telesys-api-ingress
