apiVersion: v1
kind: Service
metadata:
  labels:
    app: telesys-api
  name: telesys-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: telesys-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
