name: Build and deploy

permissions:
  packages: write

on:
  push:
    branches: ["*"]

jobs:
  build-and-publish-latest:
    strategy:
      matrix:
        image: [crypto-ingress, telesys-api]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish "latest" Docker image
      uses: docker/build-push-action@v5
      env:
        image_base: ghcr.io/mmaton/infrastructure/${{ matrix.image }}
      with:
        context: applications/${{ matrix.image }}
        cache-from: type=registry,ref=${{ env.image_base }}:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags:  ${{ env.image_base }}:${{ github.sha }}, ${{ env.image_base }}:${{ github.ref_name }}

  deploy:
    env:
      KUBECONFIG: '${{ github.workspace }}/.kube/main-kubeconfig'
    runs-on: ubuntu-latest
    needs: build-and-publish-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Kubernetes Config
        run: |
          mkdir -p '${{ github.workspace }}/.kube'
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG

      - name: Apply Helmfile
        uses: helmfile/helmfile-action@v1.7.0
        with:
          helmfile-args: > 
            apply --namespace=${{ github.ref_name }} 
            --selector gainrService=true
            --set environment=${{ github.ref_name }} 
            --set image.tag="${{ github.sha }}" 
            --set influx.host="${{ secrets.influx_host }}" 
            --set influx.token="${{ secrets.influx_token }}" 
            --set mqtt.password="${{ secrets.mqtt_password }}"
            --set kraken.key="${{ secrets.kraken_key }}"
            --set kraken.secret="${{ secrets.kraken_secret }}"
            --set cryptoIngress.monitoring.sentryDSN="${{ secrets.sentry_dsn }}"
          helmfile-workdirectory: helm
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets,
            https://github.com/aslafy-z/helm-git
