name: Build and publish images

permissions:
  packages: write

on:
  push:
    branches: ["*"]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Build and publish "latest" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: crypto-ingress
        image-tag: ${{ github.sha }}z
        additional-image-tags: ${{ github.ref_name }}
        build-context: applications/crypto-ingress
        custom-args: --platform=linux/arm64,linux/amd64 --cache-from=ghcr.io/mmaton/infrastructure/crypto-ingress:${{ github.ref_name }}
  deploy:
    uses: .github/workflows/deploy.yaml@${{ github.ref }}