name: Build and publish images

permissions:
  packages: write

on:
  push:
    branches: ["*"]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish "latest" Docker image
      uses: docker/build-push-action@v5
      with:
        context: applications/crypto-ingress
        cache-from: type=registry,ref=mmaton/infrastructure/crypto-ingress:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: mmaton/infrastructure/crypto-ingress:${{ github.sha }}, mmaton/infrastructure/crypto-ingress:${{ github.ref_name }}
