name: Build and publish images

permissions:
  packages: write

on:
  push:
    branches: ["*"]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and publish "latest" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: crypto-ingress
        image-tag: ${{ github.head_ref }}.${{ github.sha }}
        build-context: applications/crypto-ingress
        custom-args: --platform=linux/arm64,linux/amd64