name: Helmfile CI

on:
  workflow_run:
    workflows: [Build and publish images]
    types:
      - completed

jobs:
  helmfile:
    name: Helmfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Apply Helmfile
        uses: hiberbee/github-action-helm@1.3.0
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        with:
          helmfile: apply --selector name=crypto-ingress --set image.tag="${{ github.sha }}" --set influx.host="${{ secrets.influx_host }}" --set influx.token="${{ secrets.influx_token }}"
          helmfile-config: helm/helmfile.yaml
          namespace: ${{ github.ref }}
